### ISSUE TITLE
Remove unnecessary line in `AccountProfileController`

### ISSUE THREAD

**Issue by mepox** [trebol-ecommerce/trebol-backend-monolith#225]
`String username = principal.getName();` is unnecessary here.

https://github.com/trebol-ecommerce/spring-boot-backend/blob/91af6a3447d69a16cdb1c7e5dc5509fbf2110357/src/main/java/org/trebol/operation/controllers/AccountProfileController.java#L55-L56

**Comment by bglamadrid** [comment]
I suggest to change the parameter passed in `updateProfileForUserWithName` to the `username` variable, instead of deleting its assignment.

**Comment by bglamadrid** [comment]
Closed in #229
