### ISSUE TITLE
Document incompatible JDKs

### ISSUE THREAD

**Issue by bglamadrid** [trebol-ecommerce/trebol-backend-monolith#258]
# Summary

I just tried and found out that under JDK19, the compilation of this app is broken.

It would be good to know if other versions newer than 11 are incompatible as well.

### Expected outcome

A JDK compatibility list added to the `README`, near the `Requirements` section.

### Additional note

JDKs can be downloaded from many several places, given the current state of Java (distributed akin to Linux).

[Check this link to know more, and also to find the recommended one for your system.](https://whichjdk.com)

**Comment by mslowiak** [comment]
Hi @bglamadrid .
Can I work on this?

**Comment by bglamadrid** [comment]
> Hi @bglamadrid . Can I work on this?

Hi there. Why, of course! Do you have any questions?
Do you want to be assigned to this?

**Comment by bglamadrid** [comment]
There @mslowiak, I assigned you the issue. Let me know if there's anything you need assistance with!

**Comment by mslowiak** [comment]
Haha yeah, your issue apeared directly as a first issue in the search results :D 

> Let me know if there's anything you need assistance with!
Will do if I will stuck somewhere, thanks!

**Comment by mslowiak** [comment]
Hey @bglamadrid!

I checked all versions between 11-21.
Looks like compatibility is broken for 19+ - I raised the [PR](https://github.com/trebol-ecommerce/trebol-backend-monolith/issues/258) with documentation

Project uses the Spring 2.x - I think regarding to their release notes that JDK 19 is supported starts from 3.x

**Comment by bglamadrid** [comment]
> Hey @bglamadrid!
> 
> I checked all versions between 11-21. Looks like compatibility is broken for 19+ - I raised the [PR](https://github.com/trebol-ecommerce/trebol-backend-monolith/issues/258) with documentation
> 
> Project uses the Spring 2.x - I think regarding to their release notes that JDK 19 is supported starts from 3.x

Awesome. The way you phrased this last bit also made me curious, so I went ahead and searched [their repo](https://github.com/spring-projects/spring-boot) to find [this little bit of documentation](https://docs.spring.io/spring-boot/docs/current-SNAPSHOT/reference/html/getting-started.html#getting-started.system-requirements) on the matter, quote:

> Spring Boot 3.2.0-SNAPSHOT requires [Java 17](https://www.java.com/) and is compatible up to and including Java 21. [Spring Framework 6.1-SNAPSHOT](https://docs.spring.io/spring-framework/reference/6.1-SNAPSHOT/) or above is also required.

And given their versioning scheme in [their github repo](https://github.com/spring-projects/spring-boot), I managed to find this for [v2.6.x](https://docs.spring.io/spring-boot/docs/2.6.x/reference/html/getting-started.html#getting-started.system-requirements) and [v2.7.x](https://docs.spring.io/spring-boot/docs/2.7.x/reference/html/getting-started.html#getting-started.system-requirements), too.

I actually did not know there was a newer minor version of 2.x, and it's even compatible with up to Java 20. So there go some more issues to deal with later on. Thanks so much @mslowiak!
