### ISSUE TITLE
Upgrade to Spring Boot v2.7

### ISSUE THREAD

**Issue by bglamadrid** [trebol-ecommerce/trebol-backend-monolith#261]
> [...] I did not know there was **a newer minor version of 2.x**, nor that it is even **compatible with up to Java 20**.

_Originally posted by @bglamadrid in https://github.com/trebol-ecommerce/trebol-backend-monolith/issues/258#issuecomment-1755622153_

**Comment by mslowiak** [comment]
@bglamadrid 
If you don't mind, I can pick up this as well ;)

**Comment by bglamadrid** [comment]
Be my guest @mslowiak :)

**Comment by bglamadrid** [comment]
Closed in favor of #263, a much more comprehensive issue at hand.
